name: CI

on:
  push:
  pull_request:
  schedule:
  # run at 7:00 on the first of every month
  - cron: '0 7 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install APT dependencies
      run: |
        apt-get install gcc
    - name: Install PIP dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Test with platformio
      run: |
        pio test -e native
